# Generated by Django 4.2 on 2023-04-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'Podane przez ciebie imię ma więcej niż 50 znaków'}, max_length=50),
        ),
    ]
