# Generated by Django 4.2 on 2023-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Musisz podać imię', 'max_length': 'Twoje imię nie może być dłuższe niż 50 znaków', 'null': 'Musisz podać imię'}, max_length=50),
        ),
    ]
