# Generated by Django 4.2 on 2023-07-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_able_to_buy'),
        ('users', '0007_address_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='known_languages',
            field=models.ManyToManyField(blank=True, null=True, to='classes.language'),
        ),
    ]
