# Generated by Django 4.2 on 2023-10-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_privatemessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='content',
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('kobieta', 'kobieta'), ('mężczyzna', 'mężczyzna')], max_length=20, null=True),
        ),
    ]
