# Generated by Django 4.2 on 2023-07-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_able_to_buy'),
        ('users', '0008_alter_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='known_languages',
            field=models.ManyToManyField(blank=True, to='classes.language'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
