# Generated by Django 4.2 on 2023-08-01 19:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userdetails_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='place_of_classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U ucznia'), ('online', 'Online')], max_length=150, null=True),
        ),
    ]
