# Generated by Django 4.2 on 2023-08-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0013_userdetails_place_of_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cities_of_work',
            field=models.ManyToManyField(related_name='cities_of_work', to='cities_light.city'),
        ),
    ]
