# Generated by Django 4.2 on 2023-08-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0015_alter_address_city_alter_userdetails_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='voivodeship',
            field=models.ForeignKey(limit_choices_to={'country__name': 'Poland'}, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('mężczyzna', 'mężczyzna'), ('kobieta', 'kobieta')], max_length=20, null=True),
        ),
    ]
