# Generated by Django 4.2 on 2024-01-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_address_user_alter_userdetails_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
