# Generated by Django 4.2 on 2023-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0020_alter_userdetails_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cities_of_work',
            field=models.ManyToManyField(blank=True, null=True, related_name='cities_of_work', to='cities_light.city'),
        ),
    ]
