# Generated by Django 4.2 on 2023-08-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_userdetails_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('kobieta', 'kobieta'), ('mężczyzna', 'mężczyzna')], max_length=20, null=True),
        ),
    ]
