# Generated by Django 4.2 on 2023-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_userdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('kobieta', 'kobieta'), ('mężczyzna', 'mężczyzna')], max_length=20, null=True),
        ),
    ]
