# Generated by Django 4.2 on 2023-08-30 17:26

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(blank=True, upload_to=rooms.models.file_upload_path),
        ),
    ]
