# Generated by Django 4.2 on 2023-10-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='classes_rated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
