# Generated by Django 4.2 on 2023-10-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_opinion_classes_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='classes_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
