# Generated by Django 4.2 on 2023-05-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_language_class_language_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='type_of_classes_id',
            new_name='type_of_classes',
        ),
    ]
