# Generated by Django 4.2 on 2023-10-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetails_sex'),
        ('classes', '0005_askclasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askclasses',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
