# Generated by Django 4.2 on 2023-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_rename_language_id_class_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='able_to_buy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
