# Generated by Django 4.2 on 2023-10-28 06:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetails_sex'),
        ('classes', '0006_alter_askclasses_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='cities_of_classes',
        ),
        migrations.AddField(
            model_name='class',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='class',
            name='place_of_classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('online', 'Online')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('online', 'Online')], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('online', 'Online')], null=True),
        ),
    ]
