# Generated by Django 4.2 on 2023-07-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_class_able_to_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 – 10:00'), (1, '11:00 – 12:00'), (2, '12:00 – 13:00'), (3, '13:00 – 14:00'), (4, '14:00 – 15:00'), (5, '15:00 – 16:00'), (6, '16:00 – 17:00'), (7, '17:00 – 18:00'), (8, '18:00 – 19:00')])),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'date', 'timeslot')},
            },
        ),
    ]
