# Generated by Django 4.2 on 2023-11-01 06:28

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userdetails_sex'),
        ('classes', '0007_remove_class_cities_of_classes_class_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='city_of_classes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='city_of_classes',
        ),
        migrations.AddField(
            model_name='askclasses',
            name='bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='class',
            name='place_of_classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U studenta'), ('online', 'Online')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U studenta'), ('online', 'Online')], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U studenta'), ('online', 'Online')], null=True),
        ),
    ]
