# Generated by Django 4.2 on 2023-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_schedule_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
