# Generated by Django 4.2 on 2023-08-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_message'),
        ('classes', '0012_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='amount_of_lessons',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.timeslot'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
