# Generated by Django 4.2 on 2023-08-11 05:56

import classes.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0014_remove_class_type_of_classes_delete_typeofclasses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, validators=[classes.validators.validate_teacher_role]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (0, 'SUNDAY')]),
        ),
    ]
