# Generated by Django 4.2 on 2023-08-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_remove_schedule_timeslot_schedule_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
    ]
