# Generated by Django 4.2 on 2023-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_remove_schedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
