# Generated by Django 4.2 on 2023-08-11 06:59

import classes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_schedule_datetime_alter_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='hour',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, validators=[classes.validators.validate_future_date]),
        ),
    ]
