# Generated by Django 4.2 on 2023-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_remove_schedule_datetime_remove_schedule_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U ucznia'), ('online', 'Online')], null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('teacher_home', 'U nauczyciela'), ('student_home', 'U ucznia'), ('online', 'Online')], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
