# Generated by Django 4.2 on 2023-08-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_purchasehistory_place_of_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='paid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('classes', 'date')},
        ),
    ]
