# Generated by Django 4.2 on 2023-09-01 10:07

import classes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_purchasehistory_paid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, validators=[classes.validators.validate_future_date]),
        ),
    ]
