# Generated by Django 4.2 on 2023-09-02 12:51

import classes.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0010_alter_file_file_path'),
        ('classes', '0021_alter_purchasehistory_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(validators=[classes.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, validators=[classes.validators.validate_student_role]),
        ),
    ]
