# Generated by Django 4.2 on 2023-09-08 10:39

import classes.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0025_remove_class_difficulty_level_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_teacher', to=settings.AUTH_USER_MODEL, validators=[classes.validators.validate_teacher_role]),
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('student', 'teacher')},
        ),
    ]
