# Generated by Django 4.2 on 2023-09-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_alter_opinion_content_alter_opinion_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together=set(),
        ),
    ]
