# Generated by Django 4.2 on 2023-09-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_deleted_user'),
        ('classes', '0027_alter_opinion_options_alter_opinion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room'),
        ),
    ]
