# Generated by Django 4.2 on 2023-09-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_deleted_user'),
        ('classes', '0028_alter_purchasehistory_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
