# Generated by Django 4.2 on 2023-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0029_alter_purchasehistory_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('stationary', 'Stacjonarnie'), ('online', 'Online')], null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place_of_classes',
            field=models.TextField(blank=True, choices=[('stationary', 'Stacjonarnie'), ('online', 'Online')], null=True),
        ),
    ]
