# Generated by Django 4.2 on 2023-09-17 10:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('classes', '0030_alter_purchasehistory_place_of_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='cities_of_work',
            field=models.ManyToManyField(to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='class',
            name='place_of_classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stationary', 'Stacjonarnie'), ('online', 'Online')], max_length=150, null=True),
        ),
    ]
