# Generated by Django 4.2 on 2023-09-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('classes', '0031_class_cities_of_work_class_place_of_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='city_of_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='city_of_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
    ]
