# Generated by Django 4.2 on 2023-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0032_purchasehistory_city_of_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='active',
        ),
        migrations.AlterField(
            model_name='class',
            name='able_to_buy',
            field=models.BooleanField(default=True),
        ),
    ]
