# Generated by Django 4.2 on 2023-09-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('classes', '0033_remove_class_active_alter_class_able_to_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='cities_of_work',
            field=models.ManyToManyField(blank=True, null=True, to='cities_light.city'),
        ),
    ]
