# Generated by Django 4.2 on 2023-09-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0034_alter_class_cities_of_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='cities_of_work',
            new_name='cities_of_classes',
        ),
    ]
