# Generated by Django 4.2 on 2023-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0035_rename_cities_of_work_class_cities_of_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
