# Generated by Django 4.1.7 on 2023-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'Pole username jest wymagane', 'null': 'Pole username jest wymagane', 'unique': 'Ta nazwa użytkownika just istnieje w naszej bazie'}, max_length=40, unique=True),
        ),
    ]
