# Generated by Django 4.2 on 2023-11-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userdetails_sex'),
        ('classes', '0009_remove_schedule_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
    ]
