# Generated by Django 4.2 on 2023-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_language_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='country_code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
