# Generated by Django 4.2 on 2023-10-07 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdetails_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages_from_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_messages_to_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
