# Generated by Django 4.2 on 2023-11-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userdetails_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
    ]
